name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Use the latest version

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true  # Ensures Conda is up to date
        activate-environment: test_env  # Auto-activates the environment

    - name: Set up Conda environment
      run: |
        conda config --add channels conda-forge
        conda config --add channels defaults
        conda env update --file environment.yml --prune

    - name: Cache Conda environment
      uses: actions/cache@v3
      with:
        path: /usr/share/miniconda
        key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}
        restore-keys: conda-${{ runner.os }}-

    - name: Install dependencies
      run: conda install --yes --file requirements.txt

    - name: Run tests
      run: conda run -n test_env pytest  # Ensures tests run inside the Conda environment

