name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2

    - name: Set up Conda environment
      run: |
        conda config --add channels conda-forge
        conda config --add channels defaults
        conda env create -f environment.yml

    - name: Install dependencies
      run: conda install --yes --file requirements.txt

    - name: Run tests
      run: pytest
        source $CONDA/etc/profile.d/conda.sh
        conda activate novasync
        conda install --yes flake8 pytest
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash -l {{0}}
      run: |
        conda activate novasync
        pytest
