name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2

    - name: Set up Conda environment
      run: |
        conda config --add channels conda-forge
        conda config --add channels defaults
        conda env create -f environment.yml

    - name: Install dependencies
      run: conda install --yes --file requirements.txt

    - name: Run tests
      run: pytest tests/

