name: Python Package using Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.10"
        auto-update-conda: true
        environment-file: environment.yml
        activate-environment: novasync

    - name: Install dependencies
      shell: bash-l {0}
      run: |
        conda activate novasync
        conda install --yes flake8 pytest

    - name: Lint with flake8
      shell: bash-l {0}
      run: |
        conda activate novasync
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      shell: bash-l {0}
      run: |
        conda activate novasync
        pytest
